- hosts: prod
  remote_user: root
  tasks:
    - name: Copy geoblocker jar
      copy:
        src: ../target/geoblocker.jar
        dest: /opt/geoblocker

    - name: Start geoblocker service
      systemd:
        state: restarted
        name: geoblocker
